apiVersion: v1
kind: Pod
metadata:
    name: marketfeels-client
    labels:
        app: react-front-end
spec:
    containers:
        - name: react-front-end
          image: christiangracia/stock-site-front-end:v1
          ports:
              - containerPort: 5000
